name: Main Branch Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    # 1. Tu dodajemy usługę Redis specjalnie dla środowiska testowego GitHub Actions
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # Musimy zainstalować 'redis' żeby testy mogły importować bibliotekę
        run: |
          pip install flake8 pytest redis flask

      - name: Lint
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test
        # 2. Tutaj mówimy aplikacji: "Redis jest na localhost, nie szukaj go pod nazwą 'redis'"
        env:
          REDIS_HOST: localhost
        run: pytest